import { TRObj } from '@/types/global/types'

export const NAVIGATION_SHORT_MAP: TRObj<string> = {
  javascript: 'JS',
  typescript: 'TS',
  html: 'HTML',
  design: 'DESIGN',
  vue: 'Vue',
  react: 'REACT',
  angular: 'ANGULAR',
  css: 'CSS',
  babel: 'BABEL',
  graphql: 'GRAPHQL',
  nodejs: 'NODEJS',
  forum: 'FORUM',
  deno: 'DENO',
  visualization: 'VISUALIZATION',
  util: 'UTIL',
  weekly: 'WEEKLY',
  tools: 'TOOLS',
  website: 'WEBSITE',
  zjt: 'ZJT613',
  friendlink: 'FRIENDLINK',
  elasticsearch: 'ElasticSearch',
  webassembly: 'WebAssembly',
}
