export const NAVIGATION_SHORT_MAP = {
  javascript: 'JS',
  typescript: 'TS',
  html: 'HTML',
  design: 'DESIGN',
  vue: 'Vue',
  react: 'REACT',
  angular: 'ANGULAR',
  css: 'CSS',
  babel: 'BABEL',
  graphql: 'GraphQL',
  nodejs: 'NODEJS',
  forum: 'FORUM',
  deno: 'DENO',
  visualization: 'VISUALIZATION',
  util: 'UTIL',
  weekly: 'WEEKLY',
  tools: 'TOOLS',
}
